---
- name: Update cPanel-Shared Certificates
  hosts: cpanel_shareds
  vars:
    ssl_services:
      - ftp
  roles:
    - cpanel_shared
# - name: Update GWEFA-Shared Certificates
#   hosts: shared_gwefa
#   become: true
#   vars:
#     gwefa_cert: /etc/pki/tls/certs
#     gwefa_key: /etc/pki/tls/private
#     gwefa_smtpd: /etc/postfix/ssl
#   roles:
#     - gwefa

# - name: Update Zimbra-ldap SSL Certificates
#   hosts: bronzmail_ldap
#   become: true
#   vars:
#     ldap_dir: /opt/zimbra/ssl/zimbra/commercial
#     tmp_dir: /opt/zimbra/ssl/zimbra/.tmp
#   roles:
#     - ldap

# - name: Update Proxmox-Servers Certificates
#   hosts: proxmox
#   become: true
#   vars:
#     prox_dir: /etc/pve/local
#   roles:
#     - proxmox
