---
- name: Update GWEFA-Shared Certificates
  hosts: shared_gwefa
  become: true
  vars:
    gwefa_cert: /etc/pki/tls/certs
    gwefa_key: /etc/pki/tls/private
    gwefa_smtpd: /etc/postfix/ssl
  roles:
    - gwefa
