---
- name: Update Zimbra-ldap SSL Certificates
  hosts: ldap_servers
  become: true
  remote_user: exadmn
  vars:
    ldap_dir: /opt/zimbra/ssl/zimbra/commercial
    local_dir: /var/lib/awx/projects/exa-ssl/exaservers
  roles:
    - ldap
