---
- name: Upload commercial.crt to Zimbra server
  copy:
    src: "{{ local_dir }}/exaservers.crt"
    dest: "{{ ldap_dir }}/commercial.crt"
    owner: zimbra
    group: zimbra
    mode: "0640"

- name: Upload commercial.key to Zimbra server
  copy:
    src: "{{ local_dir }}/exaservers.key"
    dest: "{{ ldap_dir }}/commercial.key"
    owner: zimbra
    group: zimbra
    mode: "0640"

- name: Verify the new SSL certificate
  command: >
    /opt/zimbra/bin/zmcertmgr verifycrt comm
    {{ ldap_dir }}/commercial.key
    {{ ldap_dir }}/commercial.crt
    {{ ldap_dir }}/commercial_ca.crt
  register: verify_output

- name: Print certificate verification result
  debug:
    var: verify_output.stdout_lines

- name: Deploy the new SSL certificate
  command: >
    /opt/zimbra/bin/zmcertmgr deploycrt comm
    {{ ldap_dir }}/commercial.crt
    {{ ldap_dir }}/commercial_ca.crt

- name: Restart Zimbra services
  command: zmcontrol restart
