---
- name: Upload commercial.key to Zimbra server
  copy:
    content: "{{ lookup('env', 'DOMAIN_KEY') }}"
    dest: "{{ ldap_dir }}/commercial.key"
    owner: zimbra
    group: zimbra
    mode: "0640"

- name: Verify the new SSL certificate
  become_user: zimbra
  command: >
    /opt/zimbra/bin/zmcertmgr verifycrt comm
    {{ ldap_dir }}/commercial.key
    {{ ldap_dir }}/"{{ lookup('env', 'DOMAIN_CRT') }}"
    {{ ldap_dir }}/"{{ lookup('env', 'CA_BUNDLE_CRT') }}"
  register: verify_output

- name: Print certificate verification result
  debug:
    var: verify_output.stdout_lines

- name: Stop Zimbra-Ldap services on ldap2
  become_user: zimbra
  command: /opt/zimbra/bin/zmcontrol stop
  delegate_to: dap2-examail.exaservers.com

- name: Deploy the new SSL certificate
  become_user: zimbra
  command: >
    /opt/zimbra/bin/zmcertmgr deploycrt comm
    {{ ldap_dir }}/"{{ lookup('env', 'DOMAIN_CRT') }}"
    {{ ldap_dir }}/"{{ lookup('env', 'CA_BUNDLE_CRT') }}"

- name: Enable SNMP and Stats services in Zimbra
  become_user: zimbra
  shell: |
    /opt/zimbra/bin/zmprov ms `zmhostname` +zimbraServiceEnabled snmp
    /opt/zimbra/bin/zmprov ms `zmhostname` +zimbraServiceEnabled stats

- name: Restart Zimbra services
  become_user: zimbra
  command: /opt/zimbra/bin/zmcontrol restart
