---
- name: Update Proxmox domain key
  copy:
    content: "{{ lookup('env', 'DOMAIN_KEY') }}"
    dest: "{{ prox_dir }}/pveproxy-ssl.key"
    owner: root
    group: www-data
    mode: "0640"
  notify: Restart Pveproxy

- name: Update Proxmox pveproxy-ssl
  copy:
    content: "{{ lookup('env', 'DOMAIN_CRT') }}\n{{ lookup('env', 'CA_BUNDLE_CRT') }}"
    dest: "{{ prox_dir }}/pveproxy-ssl.pem"
    owner: root
    group: www-data
    mode: "0640"
  notify: Restart Pveproxy
