---
- name: Install SSL certificate for cPanel-{{ item }} service
  command: >
    /usr/sbin/whmapi1 install_service_ssl_certificate
    service={{ item }}
    crt='{{ lookup('env', 'DOMAIN_CRT') }}'
    key='{{ lookup('env', 'DOMAIN_KEY') }}'
    cabundle='{{ lookup('env', 'CA_BUNDLE_CRT') }}'
  loop: "{{ ssl_services }}"
