- name: Update SSL Certificates on GWEFA Servers
  hosts: gwefa
  become: true
  vars:
    local_cert_dir: /path/to/local/awx/certs # Change to actual cert path on AWX
    remote_crt: /etc/pki/tls/certs/domain.crt
    remote_key: /etc/pki/tls/private/domain.key
    remote_pem: /etc/postfix/ssl/smtpd.pem
    remote_tmp_dir: /tmp/gwefa_certs

  tasks:
    - name: Ensure remote temporary directory exists
      file:
        path: "{{ remote_tmp_dir }}"
        state: directory
        mode: "0755"

    - name: Upload domain.crt
      copy:
        src: "{{ local_cert_dir }}/domain.crt"
        dest: "{{ remote_crt }}"
        owner: root
        group: root
        mode: "0644"
      notify: Restart HTTPD

    - name: Upload domain.key
      copy:
        src: "{{ local_cert_dir }}/domain.key"
        dest: "{{ remote_key }}"
        owner: root
        group: root
        mode: "0600"
      notify: Restart HTTPD

    - name: Upload CA bundle to temp location
      copy:
        src: "{{ local_cert_dir }}/domain_ca_bundle.crt"
        dest: "{{ remote_tmp_dir }}/domain_ca_bundle.crt"
        owner: root
        group: root
        mode: "0644"

    - name: Re-upload domain.crt to temp location
      copy:
        src: "{{ local_cert_dir }}/domain.crt"
        dest: "{{ remote_tmp_dir }}/domain.crt"
        owner: root
        group: root
        mode: "0644"

    - name: Concatenate domain.crt and CA bundle into smtpd.pem
      shell: |
        cat {{ remote_tmp_dir }}/domain.crt {{ remote_tmp_dir }}/domain_ca_bundle.crt > {{ remote_pem }}
      args:
        creates: "{{ remote_pem }}"
      notify:
        - Restart Postfix
        - Restart HTTPD

    - name: Ensure smtpd.pem has correct permissions
      file:
        path: "{{ remote_pem }}"
        owner: root
        group: root
        mode: "0644"

  handlers:
    - name: Restart Postfix
      service:
        name: postfix
        state: restarted

    - name: Restart HTTPD
      service:
        name: httpd
        state: restarted
